# Sites to Enable (Available Values: subsource,subdl,altyazidb,turkcealtyazi,opensubtitles)
sites_to_search=subsource

# Default Search Language on Launch
preferred_language=en

# Sort Results (Available Values: quality, date)
sorting=

# User Agent for cURL
useragent=Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/147.0.0.0 Safari/537.36

# File Types
video_types=mkv,mp4,avi,ts,m2ts,ogm,wmv
subtitle_types=srt,ass,ssa,vtt,sub,sup,pgs,smi,idx
archive_types=zip,rar,7z

# I don't want AI translations.
block_ai=no

# Choose a program to open the archive. (Available Values: 7zip, winrar)
extract_engine=7zip

# Appends the download source information to the subtitle file name. (<moviename><sitename><subtitleid><lang>)
# Note: Windows users may experience a half-second delay when opening the interface due to PowerShell startup overhead.
append_source_to_filename=no

# Go to URL (Available Tags: <imdbid>, <title>)
goto_url_formovies=https://www.imdb.com/title/<imdbid>/
goto_url_forseries=https://www.imdb.com/title/<imdbid>/

# SECRETS
# Credentials format is username:password.

api_subsource=
api_altyazidb=
credentials_opensubtitles=

# GUI

text_size=24
sub_text_size=16
box_alpha=70
box_color=000000
cursor_color=white
padding=10
round=8
pin_right_margin=35
icon_right_margin=25
date_format=<mm>-<dd>-<yyyy>
bar_width=4
column_width=15
tag_padding=4
tag_right_margin=8