# Sites to enable (available values: subsource,subdl,altyazidb,turkcealtyazi)
sites_to_search=subsource,subdl

# Default search language on launch
preferred_language=en

# Prioritizes subtitle rows matching the video quality
smart_sorting=yes

# User Agent for cURL
useragent=Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/147.0.0.0 Safari/537.36

# File Types
video_types=mkv,mp4,avi,ts,m2ts,ogm
subtitle_types=srt,ass,ssa,vtt,sub,sup,pgs
archive_types=zip,rar,7z

# API KEYS
api_subsource=
api_subdl=
api_altyazidb=

# GUI
text_size=24
sub_text_size=16
box_alpha=70
box_color=000000
cursor_color=white
padding=10
round=8
pin_right_margin=35
icon_right_margin=25
date_format=<mm>-<dd>-<yyyy>
bar_width=4
column_width=15
tag_padding=4
tag_right_margin=8